#!/usr/bin/env python3
"""Regenerate BOARD.md — the ticket-master's live view of the pipeline.

Machine section (everything above the CONTROLLER marker) is rebuilt from Linear +
GitHub on every run. Everything below the marker is hand-maintained and preserved.

    python3 tools/board.py            # rewrite BOARD.md
    python3 tools/board.py --print    # dump to stdout, don't touch the file
"""
import json, os, re, subprocess, sys, datetime, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BOARD = os.path.join(ROOT, "BOARD.md")
MARKER = "<!-- CONTROLLER: hand-maintained below this line; board.py never touches it -->"
ENV = "/etc/clustr-agent/dispatcher.env"
REPOS = ["Clustr-ai/clustr_app", "Clustr-ai/clustr-ops"]

# WIP caps — the governor. Feeding AI Ready past these just moves the jam downstream.
CAPS = {"AI Ready": 12, "AI Processing": 10, "AI Review": 8, "Deployed to Staging": 15}

# Risk classification. A = land on green, no human read. C = full review + staging proof.
HIGH_RISK = re.compile(
    r"(migrations?/|\.sql$|infra/|terraform|\.github/workflows/|helm|"
    r"charts?/|auth|tenant|billing|secret|iam)", re.I)
LOW_RISK_ONLY = re.compile(r"(\.md$|\.lock$|package-lock\.json$|go\.sum$|go\.mod$)", re.I)


def env(name):
    for line in open(ENV):
        if line.startswith(name + "="):
            return line.split("=", 1)[1].strip()
    return ""


def linear(query, variables=None):
    req = urllib.request.Request(
        "https://api.linear.app/graphql",
        data=json.dumps({"query": query, "variables": variables or {}}).encode(),
        headers={"Authorization": env("LINEAR_API_KEY"), "Content-Type": "application/json"})
    # The URL is a module constant from dispatcher.config, set from the
    # environment at startup -- not built from request or user input, so there is
    # nothing here that can be redirected at runtime.
    # nosemgrep: python.lang.security.audit.dynamic-urllib-use-detected.dynamic-urllib-use-detected
    return json.load(urllib.request.urlopen(req))["data"]


def gh(args):
    for _ in range(3):
        p = subprocess.run(["gh"] + args, capture_output=True, text=True)
        if p.returncode == 0 and p.stdout.strip():
            return json.loads(p.stdout)
    return []


def fetch_issues():
    q = """query($c:String){ issues(first:250, after:$c, filter:{team:{key:{eq:"CLU"}},
      state:{type:{nin:["completed","canceled"]}}}){ pageInfo{hasNextPage endCursor}
      nodes{ identifier title url updatedAt state{name} priority estimate
             labels(first:8){nodes{name}} } } }"""
    out, cur = [], None
    while True:
        d = linear(q, {"c": cur})["issues"]
        out += d["nodes"]
        if not d["pageInfo"]["hasNextPage"]:
            return out
        cur = d["pageInfo"]["endCursor"]


def fetch_prs(repo):
    owner, name = repo.split("/")
    q = """query($o:String!,$n:String!){ repository(owner:$o,name:$n){
      pullRequests(states:OPEN, first:100, orderBy:{field:CREATED_AT,direction:DESC}){ nodes{
        number title url createdAt isDraft mergeable baseRefName headRefName
        additions deletions changedFiles
        author{login}
        files(first:100){nodes{path}}
        commits(last:1){nodes{commit{statusCheckRollup{state}}}}
      } } } }"""
    d = gh(["api", "graphql", "-f", f"query={q}", "-F", f"o={owner}", "-F", f"n={name}"])
    if not d:
        return []
    out = []
    for p in d["data"]["repository"]["pullRequests"]["nodes"]:
        rollup = (p["commits"]["nodes"] or [{}])[0].get("commit", {}).get("statusCheckRollup")
        p["checks"] = (rollup or {}).get("state", "NONE")
        p["repo"] = repo
        p["paths"] = [f["path"] for f in p["files"]["nodes"]]
        out.append(p)
    return out


def risk(pr):
    if (pr["author"] or {}).get("login", "").startswith("dependabot"):
        return "A"
    if pr["paths"] and all(LOW_RISK_ONLY.search(x) for x in pr["paths"]):
        return "A"
    if pr["changedFiles"] > 30 or any(HIGH_RISK.search(x) for x in pr["paths"]):
        return "C"
    return "B"


def ticket_of(pr):
    m = re.search(r"CLU-(\d+)", pr["headRefName"] + " " + pr["title"], re.I)
    return f"CLU-{m.group(1)}" if m else ""


def days(iso, today):
    return (today - datetime.datetime.strptime(iso[:10], "%Y-%m-%d").date()).days


def main():
    today = datetime.date.today()
    issues = fetch_issues()
    prs = [p for r in REPOS for p in fetch_prs(r)]
    by_state = {}
    for i in issues:
        by_state.setdefault(i["state"]["name"], []).append(i)
    pr_by_ticket = {}
    for p in prs:
        t = ticket_of(p)
        if t:
            pr_by_ticket.setdefault(t, []).append(p)

    L = []
    add = L.append
    add(f"# Fleet board — {today.isoformat()}")
    add("")
    add(f"_Machine section regenerated by `tools/board.py`. Last run: {today.isoformat()}._")
    add("")
    add("## Lanes")
    add("")
    add("| Lane | Count | Cap | State |")
    add("|---|---:|---:|---|")
    for lane in ["Backlog", "AI Ready", "AI Processing", "AI Review", "AI Awaiting Input",
                 "AI Blocked", "In Progress", "In Review", "Deployed to Staging",
                 "Deployed to Prod"]:
        n = len(by_state.get(lane, []))
        cap = CAPS.get(lane, "")
        flag = ""
        if cap and n > cap:
            flag = f"🔴 over cap by {n - cap}"
        elif cap and n == 0:
            flag = "⚪ starved"
        elif cap:
            flag = f"🟢 room for {cap - n}"
        add(f"| {lane} | {n} | {cap or '—'} | {flag} |")
    add("")

    add("## Review queue — open PRs")
    add("")
    add("Risk: **A** land on green (no human read) · **B** /code-review + intent check · "
        "**C** /code-review high + security-review + staging proof.")
    add("")
    add("| PR | Base | Ticket | Risk | Files | Δ | Mergeable | Checks | Age | Title |")
    add("|---|---|---|---|---:|---|---|---|---:|---|")
    for p in sorted(prs, key=lambda x: (risk(x), -days(x["createdAt"], today))):
        t = ticket_of(p)
        age = days(p["createdAt"], today)
        mrg = {"MERGEABLE": "ok", "CONFLICTING": "⚠️ conflict", "UNKNOWN": "?"}.get(p["mergeable"], p["mergeable"])
        chk = {"SUCCESS": "🟢", "FAILURE": "🔴", "PENDING": "🟡", "ERROR": "🔴", "NONE": "—"}.get(p["checks"], p["checks"])
        add(f"| [#{p['number']}]({p['url']}) | {p['baseRefName']} | {t or '—'} | {risk(p)} | "
            f"{p['changedFiles']} | +{p['additions']}/-{p['deletions']} | {mrg} | {chk} | {age}d | "
            f"{p['title'][:60]} |")
    add("")

    stale = [p for p in prs if days(p["createdAt"], today) > 21 and p["mergeable"] == "CONFLICTING"]
    if stale:
        add(f"### ⚠️ Stale + conflicting ({len(stale)}) — rebase-or-kill decision needed")
        add("")
        for p in sorted(stale, key=lambda x: x["number"]):
            add(f"- #{p['number']} ({days(p['createdAt'], today)}d, {p['changedFiles']} files) "
                f"{ticket_of(p) or ''} — {p['title'][:70]}")
        add("")

    for lane in ["AI Review", "AI Blocked", "AI Awaiting Input"]:
        items = by_state.get(lane, [])
        if not items:
            continue
        add(f"## {lane} ({len(items)})")
        add("")
        for i in sorted(items, key=lambda x: x["updatedAt"]):
            linked = pr_by_ticket.get(i["identifier"], [])
            prtxt = ", ".join(f"#{p['number']}" for p in linked) or "**no open PR**"
            add(f"- `{i['identifier']}` {days(i['updatedAt'], today)}d — {prtxt} — {i['title'][:70]}")
        add("")

    orphan = [i for i in by_state.get("AI Review", []) if i["identifier"] not in pr_by_ticket]
    if orphan:
        add(f"### Tickets in AI Review with no open PR ({len(orphan)}) — close or re-queue")
        add("")
        for i in orphan:
            add(f"- `{i['identifier']}` — {i['title'][:70]}")
        add("")

    machine = "\n".join(L)
    controller = ""
    if os.path.exists(BOARD):
        old = open(BOARD).read()
        if MARKER in old:
            controller = old.split(MARKER, 1)[1]
    if not controller:
        controller = "\n\n## Decisions\n\n_(append dated decisions here)_\n\n## Next actions\n\n- [ ] \n"
    doc = machine + "\n" + MARKER + controller
    if "--print" in sys.argv:
        print(doc)
    else:
        open(BOARD, "w").write(doc)
        print(f"wrote {BOARD} ({len(doc)} bytes)")


if __name__ == "__main__":
    main()
